"""Canonical Switchboard contracts. See docs/API_CONTRACTS.md and docs/DATA_MODEL.md."""

from switchboard_schemas.api import (
    AttributionListResponse,
    CallDetailResponse,
    CallListResponse,
    CallSessionSummary,
    CampaignListResponse,
    ErrorBody,
    ExtractRequest,
    ExtractResponse,
    FindingListResponse,
    HealthResponse,
    IssueStreamTokenRequest,
    IssueStreamTokenResponse,
    MockStatusWebhook,
    MockVoiceWebhook,
    StatusAccepted,
    TelephonyWebhookAck,
    TranscriptListResponse,
    ValidateStreamTokenRequest,
    ValidateStreamTokenResponse,
    VoiceInstruction,
)
from switchboard_schemas.attribution import Campaign, CampaignAttribution
from switchboard_schemas.common import (
    CONTRACT_VERSION,
    SWITCHBOARD_ID_NAMESPACE,
    Confidence,
    ContractModel,
)
from switchboard_schemas.enums import (
    CallState,
    CampaignStatus,
    CarrierProvider,
    EventType,
    FindingKind,
    FindingStatus,
    MediaStreamState,
    Producer,
    RecordLayer,
    Speaker,
    TranscriptSource,
)
from switchboard_schemas.events import EventEnvelope, validate_event
from switchboard_schemas.hotpath import ResponseDecision, ResponseRequest
from switchboard_schemas.interpretations import ConversationTurn, IntelligenceFinding
from switchboard_schemas.media import MEDIA_PROTOCOL, StreamReady
from switchboard_schemas.observations import (
    CallSession,
    MediaStream,
    OperatorNumber,
    TranscriptSegment,
    WebhookReceipt,
)

__all__ = [
    "CONTRACT_VERSION",
    "MEDIA_PROTOCOL",
    "SWITCHBOARD_ID_NAMESPACE",
    "AttributionListResponse",
    "CallDetailResponse",
    "CallListResponse",
    "CallSession",
    "CallSessionSummary",
    "CallState",
    "Campaign",
    "CampaignAttribution",
    "CampaignListResponse",
    "CampaignStatus",
    "CarrierProvider",
    "Confidence",
    "ContractModel",
    "ConversationTurn",
    "ErrorBody",
    "EventEnvelope",
    "EventType",
    "ExtractRequest",
    "ExtractResponse",
    "FindingKind",
    "FindingListResponse",
    "FindingStatus",
    "HealthResponse",
    "IntelligenceFinding",
    "IssueStreamTokenRequest",
    "IssueStreamTokenResponse",
    "MediaStream",
    "MediaStreamState",
    "MockStatusWebhook",
    "MockVoiceWebhook",
    "OperatorNumber",
    "Producer",
    "RecordLayer",
    "ResponseDecision",
    "ResponseRequest",
    "Speaker",
    "StatusAccepted",
    "StreamReady",
    "TelephonyWebhookAck",
    "TranscriptListResponse",
    "TranscriptSegment",
    "TranscriptSource",
    "ValidateStreamTokenRequest",
    "ValidateStreamTokenResponse",
    "VoiceInstruction",
    "WebhookReceipt",
    "validate_event",
]
